        <!--====== Page title area Start ======-->
        <section class="page-title-area" style="background-image: url('assets/img/home/banner.png');">
        <div class="container">
            <div class="page-title-content text-center">
                <h1 class="page-title" style="color: white;">Terms and Conditions</h1>

                <ul class="breadcrumb-nav">
                    <li><a href="/" style="color: white;">Home</a></li>
                    <li class="active" style="color: white;">Terms and Conditions</li>
                </ul>
            </div>
        </div>
    </section>
    <!--====== Page title area End ======-->

    <section class="service-details-area p-t-130 p-b-80">
        <div class="container">
            <div class="service-details-content">
                
                <h2 class="service-title p-b-40">Terms and Conditions</h2>

                
<p class="p-b-10">CRC reserves the right to update and change the Terms of Service from time to time without notice. Any new features that augment or enhance the current Service, including the release of new tools and resources, shall be subject to the Terms of Service. Continued use of the Service after any such changes shall constitute your consent to such changes. </p>
<h3 class="p-b-20 p-t-20">Account Terms</h3>
<p class="p-b-10">You must be 13 years or older to use this Service.</p>
<p class="p-b-10">You must be a human. Accounts registered by “bots” or other automated methods are not permitted.</p>
<p class="p-b-10">You must provide your legal full name, a valid email address, and any other information requested in order to complete the signup process.</p>
<p class="p-b-10">Your login may only be used by one person – a single login shared by multiple people is not permitted. You may create separate logins for as many people as you'd like.</p>
<p class="p-b-10">You are responsible for maintaining the security of your account and password. CRC cannot and will not be liable for any loss or damage from your failure to comply with this security obligation.</p>
<p class="p-b-10">You are responsible for all Content posted and activity that occurs under your account (even when Content is posted by others who have accounts under your account).</p>
<p class="p-b-10">You must not misrepresent yourself or take on the identity of someone else while using this service.</p>
<p class="p-b-10">If you are using a free account you are not permitted to block ads.</p>
<p class="p-b-10">One person or legal entity may not sign up for more than one free trial account.</p>
<p class="p-b-10">You may not use the Service for any illegal or unauthorized purpose. You must not, in the use of the Service, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
<p class="p-b-10">Violation of any of these agreements will result in the termination of your Account. While CRC prohibits such conduct and Content on the Service, you understand and agree that CRC cannot be responsible for the Content posted on the Service and you nonetheless may be exposed to such materials. You agree to use the Service at your own risk.</p>
<h3 class="p-b-20 p-t-20">Payment, Refunds, Upgrading and Downgrading Terms</h3>
<p class="p-b-10">A valid credit card is required for paying accounts.</p>
<p class="p-b-10">The Service is billed in advance on a monthly basis and is non-refundable past 30 days. There will be no refunds or credits for partial months of service, upgrade/downgrade refunds, or refunds for months unused with an open account. In order to treat everyone equally, no exceptions will be made past 30 days.</p>
<p class="p-b-10">All fees are exclusive of all taxes, levies, or duties imposed by taxing authorities, and you shall be responsible for payment of all such taxes, levies, or duties, excluding only United States (federal or state) taxes.</p>
<p class="p-b-10">For any upgrade or downgrade in plan level, your credit card that you provided will automatically be charged the new rate on your next billing cycle.</p>
<p class="p-b-10">Downgrading your Service may cause the loss of Content, features, or capacity of your Account. CRC does not accept any liability for such loss.</p>
<h3 class="p-b-20 p-t-20">Cancellation and Termination</h3>
<p class="p-b-10">You are solely responsible for properly cancelling your account. An email or phone request to cancel your account is not considered cancellation. You can cancel your account at any time by clicking on the My Account tab in the global navigation bar at the top of the screen. The My Account screen provides a simple no questions asked cancellation link.</p>
<p class="p-b-10">All of your Content (text and files) will be immediately deleted from CRC upon cancellation. This information cannot be recovered once your account is cancelled.</p>
<p class="p-b-10">If you cancel CRC before the end of your current paid up month, your cancellation will take effect immediately and you will not be charged again, but you are responsible for all charges you have previously incurred.</p>
<p class="p-b-10">CRC will not continue to provide service to customers who file chargebacks.</p>
<p class="p-b-10">CRC, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of CRC, or any other CRC service, for any reason at any time. Such termination of the Service will result in the deactivation or deletion of your Account or your access to your Account, and the forfeiture and relinquishment of all Content in your Account. CRC reserves the right to refuse service to anyone for any reason at any time.</p>
<h3 class="p-b-20 p-t-20">REFUNDS FOR HARD GOODS</h3>
<p class="p-b-10">If you have purchased a “hard good” (for example, a book or other tangible product) from {{$app->request->get('api_name')}} Cloud or any related brands, you may receive a limited refund if you comply with the following conditions (unless otherwise specified):</p>
<ol style="list-style-type: upper-roman;">
<p class="p-b-10">You must request a refund in writing by contacting<a href="mailto:{{$app->request->get('api_email')}}">{{$app->request->get('api_email')}}</a>;</p>
<p class="p-b-10">Your request for a refund must be made within thirty (30) days of your purchase;</p>
<p class="p-b-10">You must return the hard goods to {{$app->request->get('api_name')}} Cloud immediately, according to the shipping and other instructions you will receive by email after requesting a refund;</p>
<p class="p-b-10">The hard goods must be returned to {{$app->request->get('api_name')}} Cloud in like-new, or re-sellable condition, as determined in {{$app->request->get('api_name')}} Clouds’ sole, reasonable discretion.</p>
<h3 class="p-b-20 p-t-20">Modifications to the Service and Prices</h3>
<p class="p-b-10">CRC reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice.</p>
<p class="p-b-10">Prices of all CRC products and services, including but not limited to monthly subscription plan fees to CRC, are subject to change upon 30 days notice from us. Such notice may be provided at any time by posting the changes to the {{$app->request->get('api_name')}} Cloud Site (www.{{$app->request->get('api_domain')}}) or CRC itself.</p>
<p class="p-b-10">CRC shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of CRC.</p>
<h3 class="p-b-20 p-t-20">Copyright and Content Ownership</h3>
<p class="p-b-10">All content posted on CRC is must comply with U.S. copyright law. Please review our copyright compliance policy.</p>
<p class="p-b-10">CRC does not pre-screen Content, but CRC and its designee have the right (but not the obligation) in their sole discretion to refuse or remove any Content that is available via CRC.</p>
<p class="p-b-10">The look and feel of CRC is copyright ©2011-2019 {{$app->request->get('api_name')}} Cloud. All rights reserved. You may not duplicate, copy, or reuse any portion of the HTML/CSS or visual design elements without express written permission from CRC.</p>
<h3 class="p-b-20 p-t-20">General Conditions</h3>
<p class="p-b-10">Your use of CRC is at your sole risk. The service is provided on an “as is” and “as available” basis.</p>
<p class="p-b-10">Technical support is only provided to paying account holders and is only available via email.</p>
<p class="p-b-10">You understand that CRC uses third party vendors and hosting partners to provide the necessary hardware, software, networking, storage, and related technology required to run the Service.</p>
<p class="p-b-10">You must not modify, adapt or hack the Service or modify another website so as to falsely imply that it is associated with the Service, CRC, or any other CRC service.</p>
<p class="p-b-10">You may not reverse engineer or reuse source code that is in public view. This includes any and all javascript. The code is copyright CRC.</p>
<p class="p-b-10">You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, computer code that powers the Service, or access to the Service without the express written permission by CRC.</p>
<p class="p-b-10">We may, but have no obligation to, remove Content and Accounts containing Content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</p>
<p class="p-b-10">Verbal, physical, written or other abuse (including threats of abuse or retribution) of any CRC customer, employee, member, or officer will result in immediate account termination.</p>
<p class="p-b-10">You understand that the technical processing and transmission of the Service, including your Content, may be transferred, unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
<p class="p-b-10">You must not upload, post, host, or transmit unsolicited email, SMSs, or “spam” messages.</p>
<p class="p-b-10">You must not transmit any worms or viruses or any code of a destructive nature.</p>
<p class="p-b-10">If your bandwidth usage exceeds 300 MB/month, or significantly exceeds the average bandwidth usage (as determined solely by CRC) of other CRC customers, we reserve the right to immediately disable your account or throttle your file hosting until you can reduce your bandwidth consumption.</p>
<p class="p-b-10">CRC does not warrant that (i) the service will meet your specific requirements, (ii) the service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the service will be accurate or reliable, (iv) the quality of any products, services, information, or other material purchased or obtained by you through the service will meet your expectations, and (v) any errors in the Service will be corrected.</p>
<p class="p-b-10">You expressly understand and agree that CRC shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if CRC has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the service; (ii) the cost of procurement of substitute goods and services resulting from any goods, data, information or services purchased or obtained or messages received or transactions entered into through or from the service; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the service; or (v) any other matter relating to the service.</p>
<p class="p-b-10">The failure of CRC to exercise or enforce any right or provision of the Terms of Service shall not constitute a waiver of such right or provision. The Terms of Service constitutes the entire agreement between you and CRC and govern your use of the Service, superseding any prior agreements between you and CRC (including, but not limited to, any prior versions of the Terms of Service).</p>
<h3 class="p-b-20 p-t-20">THIRD-PARTY SCRIPTS AND SITE BUILDERS</h3>
<p class="p-b-10">MyCreditRepairSite comes with site templates and a built-in site builder. For security measures, we prohibit the use of WordPress or any other third-party site builders, page builders, or third-party scripts to be installed on our servers. Use of third party site builders, page builders, scripts, or overuse of server resources will result in immediate suspension of your hosting account, and in the case of malicious code and scripts, there will be the instant removal of all files.</p>
<p class="p-b-10">Any member acting unethical or unprofessional will be removed, at the sole discretion of {{$app->request->get('api_name')}} Cloud Software, with all product usage forfeited. Any member who distributes content that is deemed damaging to {{$app->request->get('api_name')}} Cloud Software or its members will be terminated and legal action will be pursued.</p>
<h3 class="p-b-20 p-t-20">Copy-written text, images, content, and templates</h3>
<p class="p-b-10">Our websites cannot be moved or copied or replicated to any other company. They are not traditional sites. They are more like software. They are dependent upon our server and database and we own the copyright to all of our original content (templates, text, and images). Please respect our copyright. We will enforce it to the fullest extent of the law. If you do not want to use our hosting, hire a designer, a writer, and create your own original site and content. You may not copy our text, images, template, content, or layout.</p>
<h3 class="p-b-20 p-t-20">Spam</h3>
<p class="p-b-10">We have a zero-tolerance for spam sent out by any of the sites we host. Spam includes, but is not limited to, sending emails to people who have not opted into your list, adding people to your list without their approval, or adding people back into your list who have chosen to opt-out. Violation of this can result in the cancellation of your account.</p>
<h3 class="p-b-20 p-t-20">Marketing</h3>
<p class="p-b-10">You are prohibited from using viruses (trojans, adware, bots, software, etc) to market your site or capture page. Violation of this can result in the suspension or cancellation of your account.</p>
<h3 class="p-b-20 p-t-20">Mass Emails</h3>
<p class="p-b-10">If you're planning to send mass emails, you cannot do that on our hosting. You'll need to use a 3rd party mass email service for that like MailChimp, Streamsend of ConstantContact. That's what we also do ourselves.</p>
<h3 class="p-b-20 p-t-20">Refund Policy</h3>
<p class="p-b-10">Domains are non-refundable. Monthly payments are subject to 30 day money back guarantee. Web hosting is not a profit center for us. We created this as an added service for our {{$app->request->get('api_name')}} Software users who need an easy way to have a business website.</p>
<p class="p-b-10">There are no refunds on domain names. We do not make any profit on domain names. The fee is $10/year for a domain name and that $10 is paid directly to ENOM who processes and controls the domain registration. ENOM does not give refunds even to us, so please check the spelling of your domain name before you register it. There are absolutely no refunds ever on $10 domain names. Web hosting accounts are paid in advance monthly or annually.</p>
<h3 class="p-b-20 p-t-20">The following fees are non-refundable:</h3>
<li data-list-indent="1" data-list-type="bulleted">
<p class="p-b-10">If you do not wish to be billed for hosting, please cancel your account <u>prior</u> to any charges occurring or contact us to cancel your account for you. Write a support ticket and we will cancel it for you within 24 hours.</p>
</li>
<li data-list-indent="1" data-list-type="bulleted">
<p class="p-b-10">You will always be sent an invoice 1 week prior. An invoice is not a charge. Invoices have dates and information to explain what they are.</p>
<h3 class="p-b-20 p-t-20">If you wish to cancel your web hosting account:</h3>
</li>
<li data-list-indent="1" data-list-type="bulleted">
<p class="p-b-10">Please request cancellation in a support ticket. Support tickets have a time-stamp showing exactly when you requested to cancel. Once you cancel, no new billing can occur. </p>
</li>
<li data-list-indent="1" data-list-type="bulleted">
<p class="p-b-10">Remember, we have many products and services, so take time to send a clear message in your support ticket to explain what you are canceling.</p>
</li>



<h3 class="p-b-20 p-t-20">DISCLAIMERS</h3>
<p class="p-b-10">Our software products and resources offer credit information, not legal advice. We make every effort to ensure the accuracy of the information and to clearly explain your options. However, we do not provide legal advice (i.e.; the application of the law to your individual circumstances). For legal advice, please consult an attorney, your city or your state.</p>
<p class="p-b-10">This website and software (the “Site”) are owned and operated by Daniel A. Rosen, Inc. (DBA {{$app->request->get('api_name')}} Cloud “CRC,” “we” or “us”). By using the Site, you agree to be bound by these Terms of Service and to use the Site in accordance with these Terms of Service, our Privacy Policy and any additional terms and conditions that may apply to specific sections of the Site or to products and services available through the Site or from CRC. Accessing the Site, in any manner, whether automated or otherwise, constitutes use of the Site and your agreement to be bound by these Terms of Service.</p>
<p class="p-b-10">We reserve the right to change our Terms of Service, our Disclaimers or to impose new conditions on use of the Site, from time to time, in which case we will post the revised Terms of Service on this website. By continuing to use the Site after we post any such changes, you accept the Terms of Service, as modified.</p>
<p class="p-b-10">The information in our site, books and products are provided for informational purposes only. Neither the publisher nor the author shall be liable for any physical, emotional, financial or commercial damages, including but not limited to special, incidental, consequential, or other damages caused or allegedly caused directly or indirectly, by the information in this book. The author and publisher specifically disclaim any liability incurred from the use or application of the contents of this book. This books offers information, not legal advice. We make every effort to ensure the accuracy of the information and to clearly explain your options. However, we do not provide legal advice (i.e., the application of the law to your individual circumstances). For legal advice, please consult an attorney. </p>
<p class="p-b-10">IMPORTANT: Earnings and Legal Disclaimers</p>
<p class="p-b-10">Earnings and income representations made in this site, in our books and videos are aspirational statements about earnings potential. The success stories, testimonials and other examples used are exceptional, non-typical results and are not a guarantee that you or others will achieve the same results. Individual results will always vary and yours will depend entirely on your individual capacity, work ethic, business skills, experience, level of motivation, your own diligence, the economy, the normal and unforeseen risks of doing business, and other factors. </p>
<p class="p-b-10">CRC and our employees are not responsible for your actions. You are solely responsible for your own actions and decisions and the evaluation and use of our products and services should be based on your own due diligence. You agree that CRC is not liable to you in any way for your results in using our products and services. See our Terms &amp; Conditions for our full disclaimer of liability and other restrictions.</p>
<p class="p-b-10">Throughout the Site, we may provide links and pointers to Internet sites maintained by third parties. Our linking to such third-party sites does not imply an endorsement or sponsorship of such sites, or the information, products or services offered on or through the sites. In addition, neither we nor affiliates operate or control in any respect any information, products or services that third parties may provide on or through the Site or on websites linked to by us on the Site.</p>
<p class="p-b-10">If applicable, any opinions, advice, statements, services, offers, or other information or content expressed or made available by third parties, including information providers, are those of the respective authors or distributors, and not CRC. Neither CRC nor any third-party provider of information guarantees the accuracy, completeness, or usefulness of any content. Furthermore, CRC neither endorses nor is responsible for the accuracy and reliability of any opinion, advice, or statement made on any of the Sites by anyone other than an authorized CRC representative while acting in his/her official capacity.</p>
<p class="p-b-10">Content Disclaimer</p>
<p class="p-b-10">THE CRC AND ITS OWNERS, PRINCIPALS, REPRESENTATIVES AND AGENTS ASSUME NO RESPONSIBILITY FOR ANY CONSEQUENCE RELATING DIRECTLY OR INDIRECTLY TO ANY ACTION OR INACTION YOU TAKE BASED ON THE INFORMATION, PRODUCTS, SERVICES, OR MATERIALS ON THE WEBSITE. WHILE THE CRC STRIVES TO KEEP THE INFORMATION ON THE WEBSITE AND ON THE FEATURED PRODUCTS AND SERVICES ACCURATE, COMPLETE, AND UP-TO-DATE, WE CANNOT GUARANTEE, AND WILL NOT BE RESPONSIBLE FOR, ANY DAMAGE OR LOSS RELATED TO THE ACCURACY, COMPLETENESS, OR TIMELINESS OF THE INFORMATION ON THE WEBSITE AND IN PRODUCTS AND SERVICES FEATURED ON THE WEBSITE. </p>
<p class="p-b-10">YOUR USE OF THE WEBSITE IS SUBJECT TO ANY ADDITIONAL DISCLAIMERS AND CAVEATS THAT MAY APPEAR THROUGHOUT THE WEBSITE AND WITH PRODUCTS AND SERVICES FEATURED BY US.</p>
<p class="p-b-10">Disclaimer of Warranties With Respect to Use of Website and Products and Services</p>
<p class="p-b-10">THE WEBSITE AND ALL PRODUCTS AND SERVICES FEATURED ON IT ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. EXCEPT AS SPECIFICALLY PROVIDED HEREIN, TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, THE CRC EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
<p class="p-b-10">WHILE THE CRC USES REASONABLE EFFORTS TO INCLUDE ACCURATE AND UP TO DATE INFORMATION ON THE WEBSITE, THE CRC DOES NOT MAKE ANY WARRANTY THAT THE WEBSITE WILL MEET YOUR REQUIREMENTS, OR THAT ACCESS TO THE WEBSITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, OR THAT DEFECTS, IF ANY, WILL BE CORRECTED. THE CRC MAKES NO WARRANTIES AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE OR THE PRODUCTS AND SERVICES FEATURED THEREON, OR AS TO THE ACCURACY, QUALITY, OR RELIABILITY OF ANY INFORMATION OBTAINED THROUGH THE WEBSITE.</p>
<p class="p-b-10"> </p>
<p class="p-b-10">YOU UNDERSTAND AND AGREE THAT ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE WEBSITE IS USED AT YOUR OWN RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL AND/OR DATA. </p>
<p class="p-b-10"> </p>
<p class="p-b-10">NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE CRC OR THROUGH THE WEBSITE SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
<p class="p-b-10"> </p>
<p class="p-b-10">THE INFORMATION, PRODUCTS AND SERVICES OFFERED ON OR THROUGH THE SITE AND BY CRC AND ANY THIRD-PARTY SITES ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. </p>
<p class="p-b-10"> </p>
<p class="p-b-10">WE DO NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE SITE OR MATERIALS ON THIS SITE OR ON THIRD-PARTY SITES IN TERMS OF THEIR CORRECTNESS, ACCURACY, TIMELINESS, RELIABILITY OR OTHERWISE.</p>
<p class="p-b-10">You agree at all times to defend, indemnify and hold harmless CRC its affiliates, their successors, transferees, assignees and licensees and their respective parent and subsidiary companies, agents, associates, officers, directors, shareholders and employees of each from and against any and all claims, causes of action, damages, liabilities, costs and expenses, including legal fees and expenses, arising out of or related to your breach of any obligation, warranty, representation or covenant set forth herein.</p>
<h3 class="p-b-20 p-t-20">Online Commerce</h3>
<p class="p-b-10">Certain sections of the Site may allow you to purchase many different types of products and services online that are provided by third parties. We are not responsible for the quality, accuracy, timeliness, reliability or any other aspect of these products and services. If you make a purchase from a merchant on the Site or on a site linked to by the Site, the information obtained during your visit to that merchant’s online store or site, and the information that you give as part of the transaction, such as your credit card number and contact information, may be collected by both the merchant and us. A merchant may have privacy and data collection practices that are different from ours. We have no responsibility or liability for these independent policies. In addition, when you purchase products or services on or through the Site, you may be subject to additional terms and conditions that specifically apply to your purchase or use of such products or services. For more information regarding a merchant, its online store, its privacy policies, and/or any additional terms and conditions that may apply, visit that merchant’s website and click on its information links or contact the merchant directly. You release us and our affiliates from any damages that you incur, and agree not to assert any claims against us or them, arising from your purchase or use of any products or services made available by third parties through the Site.</p>
<p class="p-b-10">Your participation, correspondence or business dealings with any third party found on or through our Site, regarding payment and delivery of specific goods and services, and any other terms, conditions, representations or warranties associated with such dealings, are solely between you and such third party. You agree that CRC shall not be responsible or liable for any loss, damage, or other matters of any sort incurred as the result of such dealings.</p>
<p class="p-b-10">You agree to be financially responsible for all purchases made by you or someone acting on your behalf through the Site. You agree to use the Site and to purchase services or products through the Site for legitimate, non-commercial purposes only. You also agree not to make any purchases for speculative, false or fraudulent purposes or for the purpose of anticipating demand for a particular product or service. You agree to only purchase goods or services for yourself or for another person for whom you are legally permitted to do so. When making a purchase for a third party that requires you to submit the third party’s personal information to us or a merchant, you represent that you have obtained the express consent of such third party to provide such third party’s personal information.</p>
<p class="p-b-10">Your purchase is for personal use only. Sharing of purchases is not permitted and will be considered unauthorized, an infringing use of our copyrighted material, and may subject violators to liability.</p>
<p class="p-b-10">If payment for a course is declined, our system will automatically disable access to our premium materials. (We understand this usually happens because a credit card expires). We want to help restore your access, so we’ll make every attempt to contact you to help resolve this issue. Once the billing issue is resolved, we’ll restore access.</p>
<h3 class="p-b-20 p-t-20">Interactive Features</h3>
<p class="p-b-10">This Site may include a variety of features, such as bulletin boards, web logs, chat rooms, and email services, which allow feedback to us and real-time interaction between users, and other features which allow users to communicate with others. Responsibility for what is posted on bulletin boards, web logs, chat rooms, and other public posting areas on the Site, or sent via any email services on the Site, lies with each user – you alone are responsible for the material you post or send. We do not control the messages, information or files that you or others may provide through the Site. </p>
<p class="p-b-10">It is a condition of your use of the Site that you do not:</p>
<p class="p-b-10">Restrict or inhibit any other user from using and enjoying the Site.</p>
<p class="p-b-10">Use the Site to impersonate any person or entity, or falsely state or otherwise misrepresent your affiliation with a person or entity.</p>
<p class="p-b-10">Interfere with or disrupt any servers or networks used to provide the Site or its features, or disobey any requirements, procedures, policies or regulations of the networks we use to provide the Site.</p>
<p class="p-b-10">Use the Site to instigate or encourage others to commit illegal activities or cause injury or property damage to any person.</p>
<p class="p-b-10">Gain unauthorized access to the Site, or any account, computer system, or network connected to this Site, by means such as hacking, password mining or other illicit means.</p>
<p class="p-b-10">Obtain or attempt to obtain any materials or information through any means not intentionally made available through this Site.</p>
<p class="p-b-10">Use the Site to post or transmit any unlawful, threatening, abusive, libelous, defamatory, obscene, vulgar, pornographic, profane or indecent information of any kind, including without limitation any transmissions constituting or encouraging conduct that would constitute a criminal offense, give rise to civil liability or otherwise violate any local, state, national or international law.</p>
<p class="p-b-10">Use the Site to post or transmit any information, software or other material that violates or infringes upon the rights of others, including material that is an invasion of privacy or publicity rights or that is protected by copyright, trademark or other proprietary right, or derivative works with respect thereto, without first obtaining permission from the owner or rights holder.</p>
<p class="p-b-10">Use the Site to post or transmit any information, software or other material that contains a virus or other harmful component.</p>
<p class="p-b-10">Use the Site to post, transmit or in any way exploit any information, software or other material for commercial purposes, or that contains advertising.</p>
<p class="p-b-10">Use the Site to advertise or solicit to anyone to buy or sell products or services, or to make donations of any kind, without our express written approval.</p>
<p class="p-b-10">Gather for marketing purposes any email addresses or other personal information that has been posted by other users of the Site.</p>
<p class="p-b-10">CRC may host message boards, chats and other public forums on its Sites. Any user failing to comply with the terms and conditions of this Agreement may be expelled from and refused continued access to, the message boards, chats or other public forums in the future. CRC or its designated agents may remove or alter any user-created content at any time for any reason. Message boards, chats and other public forums are intended to serve as discussion centers for users and subscribers. Information and content posted within these public forums may be provided by CRC staff, CRC’S outside contributors, or by users not connected with CRC, some of whom may employ anonymous user names. CRC expressly disclaims all responsibility and endorsement and makes no representation as to the validity of any opinion, advice, information or statement made or displayed in these forums by third parties, nor are we responsible for any errors or omissions in such postings, or for hyperlinks embedded in any messages. Under no circumstances will we, our affiliates, suppliers or agents be liable for any loss or damage caused by your reliance on information obtained through these forums. The opinions expressed in these forums are solely the opinions of the participants, and do not reflect the opinions of CRC or any of its subsidiaries or affiliates.</p>
<p class="p-b-10">CRC has no obligation whatsoever to monitor any of the content or postings on the message boards, chat rooms or other public forums on the Sites. However, you acknowledge and agree that we have the absolute right to monitor the same at our sole discretion. In addition, we reserve the right to alter, edit, refuse to post or remove any postings or content, in whole or in part, for any reason and to disclose such materials and the circumstances surrounding their transmission to any third party in order to satisfy any applicable law, regulation, legal process or governmental request and to protect ourselves, our clients, sponsors, users and visitors.</p>
<p class="p-b-10">We occasionally include access to an online community as part of our programs. We want every single member to add value to the group. Our goal is to make your community the most valuable community you’re a member of. Therefore, we reserve the right to remove anyone at any time. We rarely do this, but we want to let you know how seriously we take our communities.</p>
<h3 class="p-b-20 p-t-20">Registration</h3>
<p class="p-b-10">To access certain features of the Site, we may ask you to provide certain demographic information including your gender, year of birth, zip code and country. In addition, if you elect to sign-up for a particular feature of the Site, such as chat rooms, web logs, or bulletin boards, you may also be asked to register with us on the form provided and such registration may require you to provide personally identifiable information such as your name and email address. You agree to provide true, accurate, current and complete information about yourself as prompted by the Site’s registration form. If we have reasonable grounds to suspect that such information is untrue, inaccurate, or incomplete, we have the right to suspend or terminate your account and refuse any and all current or future use of the Site (or any portion thereof). Our use of any personally identifiable information you provide to us as part of the registration process is governed by the terms of our Privacy Policy.</p>
<h3 class="p-b-20 p-t-20">Passwords</h3>
<p class="p-b-10">To use certain features of the Site, you will need a username and password, which you will receive through the Site’s registration process. You are responsible for maintaining the confidentiality of the password and account, and are responsible for all activities (whether by you or by others) that occur under your password or account. You agree to notify us immediately of any unauthorized use of your password or account or any other breach of security, and to ensure that you exit from your account at the end of each session. We cannot and will not be liable for any loss or damage arising from your failure to protect your password or account information.</p>
<h3 class="p-b-20 p-t-20">Limitation of Liability</h3>
<p class="p-b-10">UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL WE, OUR SUBSIDIARY AND PARENT COMPANIES OR AFFILIATES BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES THAT RESULT FROM THE USE OF, OR THE INABILITY TO USE, THE SITE, INCLUDING OUR MESSAGING, BLOGS, COMMENTS OF OTHERS, BOOKS, EMAILS, PRODUCTS, OR SERVICES, OR THIRD-PARTY MATERIALS, PRODUCTS, OR SERVICES MADE AVAILABLE THROUGH THE SITE OR BY US IN ANY WAY, EVEN IF WE ARE ADVISED BEFOREHAND OF THE POSSIBILITY OF SUCH DAMAGES. (BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN CATEGORIES OF DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES, OUR LIABILITY AND THE LIABILITY OF OUR SUBSIDIARY AND PARENT COMPANIES OR AFFILIATES IS LIMITED TO THE FULLEST EXTENT PERMITTED BY SUCH STATE LAW.) YOU SPECIFICALLY ACKNOWLEDGE AND AGREE THAT WE ARE NOT LIABLE FOR ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF ANY USER. IF YOU ARE DISSATISFIED WITH THE SITE, ANY MATERIALS, PRODUCTS, OR SERVICES ON THE SITE, OR WITH ANY OF THE SITE’S TERMS AND CONDITIONS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE AND THE PRODUCTS, SERVICES AND/OR MATERIALS</p>
<p class="p-b-10">CRC IS NOT AN INVESTMENT ADVISORY SERVICE, IS NOT AN INVESTMENT ADVISER, AND DOES NOT PROVIDE PERSONALIZED FINANCIAL ADVICE OR ACT AS A FINANCIAL ADVISOR.</p>
<p class="p-b-10">WE EXIST FOR EDUCATIONAL PURPOSES ONLY, AND THE MATERIALS AND INFORMATION CONTAINED HEREIN AND IN OUR PRODUCTS AND SERVICES ARE FOR GENERAL INFORMATIONAL PURPOSES ONLY. NONE OF THE INFORMATION PROVIDED BY US IS INTENDED AS INVESTMENT, TAX, ACCOUNTING OR LEGAL ADVICE, AS AN OFFER OR SOLICITATION OF AN OFFER TO BUY OR SELL, OR AS AN ENDORSEMENT, RECOMMENDATION OR SPONSORSHIP OF ANY CRC, SECURITY, OR FUND. OUR INFORMATION SHOULD NOT BE RELIED UPON FOR PURPOSES OF TRANSACTING IN SECURITIES OR OTHER INVESTMENTS. WE DO NOT OFFER OR PROVIDE TAX, LEGAL OR INVESTMENT ADVICE AND YOU ARE RESPONSIBLE FOR CONSULTING TAX, LEGAL, OR FINANCIAL PROFESSIONALS BEFORE ACTING ON ANY INFORMATION PROVIDED BY US.</p>
<p class="p-b-10">THIS SITE IS CONTINUALLY UNDER DEVELOPMENT AND CRC MAKES NO WARRANTY OF ANY KIND, IMPLIED OR EXPRESS, AS TO ITS ACCURACY, COMPLETENESS OR APPROPRIATENESS FOR ANY PURPOSE.</p>
<p class="p-b-10">YOU acknowledge and agree that no representation has been made by CRC OR ITS AFFILIATES and relied upon as to the future income, expenses, sales volume or potential profitability that may be derived from the participation in THIS PROGRAM.</p>
<h3 class="p-b-20 p-t-20">Termination</h3>
<p class="p-b-10">We may cancel or terminate your right to use the Site or any part of the Site at any time without notice. In the event of cancellation or termination, you are no longer authorized to access the part of the Site affected by such cancellation or termination. The restrictions imposed on you with respect to material downloaded from the Site, and the disclaimers and limitations of liabilities set forth in these Terms of Service, shall survive.</p>
<h3 class="p-b-20 p-t-20">Refund Policy</h3>
<p class="p-b-10">Your purchase of a product or service or ticket to an event may or may not provide for any refund. Each specific product, service, event or course will specify its own refund policy.</p>
<h3 class="p-b-20 p-t-20">Other</h3>
<p class="p-b-10">The Digital Millennium Copyright Act of 1998 (the “DMCA”) provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under the U.S. copyright law. If you believe in good faith that materials hosted by CRC infringe your copyright, you, or your agent may send to CRC a notice requesting that the material be removed or access to it be blocked. Any notification by a copyright owner or a person authorized to act on its behalf that fails to comply with requirements of the DMCA shall not be considered sufficient notice and shall not be deemed to confer upon CRC actual knowledge of facts or circumstances from which infringing material or acts are evident. If you believe in good faith that a notice of copyright infringement has been wrongly filed against you, the DMCA permits you to send to CRC a counter-notice. All notices and counter notices must meet the then current statutory requirements imposed by the DMCA; see http://www.loc.gov/copyright for details. CRC’s Copyright Agent for notice of claims of copyright infringement or counter notices can be reached at the email support link at {{$app->request->get('api_domain')}}</p>
<p class="p-b-10">This Agreement shall be binding upon and inure to the benefit of CRC and our respective assigns, successors, heirs, and legal representatives. Neither this Agreement nor any rights hereunder may be assigned without the prior written consent of CRC. Notwithstanding the foregoing, all rights and obligations under this Agreement may be freely assigned by CRC to any affiliated entity or any of its wholly owned subsidiaries</p>
<p class="p-b-10">These Terms of Use shall be governed by and construed in accordance with the laws of the State of California and any dispute shall be subject to binding arbitration in CALIFORNIA. If any provision of this agreement shall be unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from this agreement and shall not affect the validity and enforceability of any remaining provisions.</p>
<h3 class="p-b-20 p-t-20">Intellectual Property Rights</h3>
<p class="p-b-10">Our Limited License to You. This Site and all the materials available on the Site are the property of us and/or our affiliates or licensors, and are protected by copyright, trademark, and other intellectual property laws. The Site is provided solely for your personal noncommercial use. You may not use the Site or the materials available on the Site in a manner that constitutes an infringement of our rights or that has not been authorized by us. More specifically, unless explicitly authorized in these Terms of Service or by the owner of the materials, you may not modify, copy, reproduce, republish, upload, post, transmit, translate, sell, create derivative works, exploit, or distribute in any manner or medium (including by email or other electronic means) any material from the Site. You may, however, from time to time, download and/or print one copy of individual pages of the Site for your personal, non-commercial use, provided that you keep intact all copyright and other proprietary notices.</p>
<p class="p-b-10">Your License to Us. By posting or submitting any material (including, without limitation, comments, blog entries, Facebook postings, photos and videos) to us via the Site, internet groups, social media venues, or to any of our staff via email, text or otherwise, you are representing: (i) that you are the owner of the material, or are making your posting or submission with the express consent of the owner of the material; and (ii) that you are thirteen years of age or older. In addition, when you submit, email, text or deliver or post any material, you are granting us, and anyone authorized by us, a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to use, copy, modify, transmit, sell, exploit, create derivative works from, distribute, and/or publicly perform or display such material, in whole or in part, in any manner or medium, now known or hereafter developed, for any purpose. The foregoing grant shall include the right to exploit any proprietary rights in such posting or submission, including, but not limited to, rights under copyright, trademark, service mark or patent laws under any relevant jurisdiction. Also, in connection with the exercise of such rights, you grant us, and anyone authorized by us, the right to identify you as the author of any of your postings or submissions by name, email address or screen name, as we deem appropriate.</p>
<p class="p-b-10">You acknowledge and agree that any contributions originally created by you for us shall be deemed a “work made for hire” when the work performed is within the scope of the definition of a work made for hire in Section 101 of the United States Copyright Law, as amended. As such, the copyrights in those works shall belong to CRC from their creation. Thus, CRC shall be deemed the author and exclusive owner thereof and shall have the right to exploit any or all of the results and proceeds in any and all media, now known or hereafter devised, throughout the universe, in perpetuity, in all languages, as CRC determines. In the event that any of the results and proceeds of your submissions hereunder are not deemed a “work made for hire” under Section 101 of the Copyright Act, as amended, you hereby, without additional compensation, irrevocably assign, convey and transfer to CRC all proprietary rights, including without limitation, all copyrights and trademarks throughout the universe, in perpetuity in every medium, whether now known or hereafter devised, to such material and any and all right, title and interest in and to all such proprietary rights in every medium, whether now known or hereafter devised, throughout the universe, in perpetuity. Any posted materials which are reproductions of prior works by you shall be co-owned by us.</p>
<p class="p-b-10">You acknowledge that CRC has the right but not the obligation to use and display any postings or contributions of any kind and that CRC may elect to cease the use and display of any such materials (or any portion thereof), at any time for any reason whatsoever.</p>
<p class="p-b-10">Limitations on Linking and Framing. You may establish a hypertext link to the Site so long as the link does not state or imply any sponsorship of your site by us or by the Site. However, you may not, without our prior written permission, frame or inline link any of the content of the Site, or incorporate into another website or other service any of our material, content or intellectual property.</p>
<h3 class="p-b-20 p-t-20">Disclaimer</h3>
<p class="p-b-10">Although it is highly unlikely, this policy may be changed at any time at our discretion. If we should update this policy, we will post the updates to this page on our Website.</p>
<h3 class="p-b-20 p-t-20">QUESTIONS</h3>
<p class="p-b-10">If you have any questions about our <a href="terms">Terms and Conditions</a>, the practices of this site, or your dealings with this site, please contact us by sending us an email to: 
<a href="mailto:{{$app->request->get('api_email')}}">{{$app->request->get('api_email')}}</a> or by mail at: {{$app->request->get('api_name')}} {{$app->request->get('api_address')}}. </p>
<p>Updated: October 6, {{date('Y')}}</p>
                 </div>
        </div>
    </section>
